language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
jdk:
  - oraclejdk8
before_install:
  - yes | sdkmanager "platforms;android-27"

  script:
   - ./gradlew build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
